### ISSUE TITLE
Layout issue with hotspot banner

### ISSUE THREAD

**Issue by UnknownDude74** [LeoNatan/LNNotificationsUI#13]
Hi @LeoNatan,

I'm having an issue if I attempt to display a notification while the hotspot banner is active. It shows up correctly but after it animates away it gets stuck. Can you replicate the results ? 
![img_0612](https://cloud.githubusercontent.com/assets/6325243/5674624/b72eef7a-97a5-11e4-8801-12da928fc1e8.PNG)

**Comment by LeoNatan** [comment]
I'll take a look, thanks for pointing it out!
