### ISSUE TITLE
Show action buttons and an input field in notification banners.

### ISSUE THREAD

**Issue by oferRounds** [LeoNatan/LNNotificationsUI#14]
It would be great if such one, similar to the one used by the Messages app, could be added.

Thanks for this really great library!

**Comment by LeoNatan** [comment]
Thanks for your suggestion, will look into it for future updates when I have the time.

**Comment by fotiDim** [comment]
That would be helpful

**Comment by cannyboy** [comment]
+1

I don't think any other in-app notification libraries have this - though I have asked about it https://github.com/hyperoslo/Whisper/issues/67

**Comment by LeoNatan** [comment]
WhatsApp recently improved their in-app notifications to include a swipe to respond feature. And it's quite a pain to use because if you swipe above a certain threshold, the iOS Notification Center picks up the gesture. So it sometimes works and sometimes doesn't.

**Comment by LeoNatan** [comment]
I am closing this one. I just don't think this works well after playing with WhatsApp's implementation. It is too close to the notification center, and pulling down in most cases opens the notification center, instead of the pan gesture of the notification.

**Comment by oferRounds** [comment]
Makes sense, thanks for the update!

**Comment by MHX792** [comment]
I still think that this feature should be implemented. Wouldn't it be possible to restrict the gesture area to the lower part of the notification banner? For an additional effect the banner's height can be slightly increased. Unfortunately I am not good at ObjC (I prefer Swift), otherwise I would have tried to implement it.

**Comment by LeoNatan** [comment]
There is no point anymore. With iOS 10, you can choose to display remote and user (new term for local) notifications natively. So really, I will be deprecating this framework soon. It is good for what it does on iOS 8 & 9, but with 10 you just get the real, native system implementation.

**Comment by cannyboy** [comment]
@LeoNatan - do you mean notifications will be shown even if the app is active?

**Comment by LeoNatan** [comment]
Yes indeed, when handling notifications using the new API (`UNUserNotificationCenterDelegate`), you have an option to specify whether the notification should be displayed inside the application.
