### ISSUE TITLE
Dismiss notification?

### ISSUE THREAD

**Issue by devios1** [LeoNatan/LNNotificationsUI#15]
I can't figure out how to hide an LNNotification once it has been shown.

**Comment by LeoNatan** [comment]
Hi,

To dismiss, either wait, tap on it or swipe up. If you tap, the notification's handler will be called if set.

**Comment by devios1337** [comment]
Sorry I meant programmatically. Is there a way to dismiss a LNNotification object?

**Comment by LeoNatan** [comment]
Not possible at this time. Please state your requirements, as they are not clear. Once the notification is shown, it will be on screen for a few seconds and perish. Is it really needed to be able to hide it faster from code? I guess it is possible to develop, I just wonder what the use case is. Thanks

**Comment by mohpor** [comment]
I'm very much in need of this feature too:
My app may display a few notifications in a root window, I might tap on one of them and go to another page (which will gracefully dismiss the notification too), but, if I tap a row in my table view and go to the same destination page (which is essentially what tap on notifications will result in too) the notification will wait out it's time and then gets dismissed.

I want to be able to dismiss the visible notification at any time. I can clear pending notifications, I know that, but if it was possible to dismiss the current notification too, that'd be awesome.

P.S.: `LNNotificationBannerWindow` already has the functionality: `- (void)dismissNotificationViewWithCompletionBlock:(void(^)())completionBlock;` and just needs a finishing touch to be able to link it to the current notification (a banner one of course) and we are good to go.

**Comment by LeoNatan** [comment]
Cheers, now it's more clear. Will see what I can do.

**Comment by LeoNatan** [comment]
@mohpor I am having a problem designing this workflow.

For you to know which notification is currently displayed, I could provide a `currentlyPresentedNotification` property, but managing such a property is difficult. For example, if notifications are presented as alerts, several notifications can overlap and when dismissing the top one, presents the previous one. Now imaging a mix of both banners and alerts.

You should change your design to not display notifications if the UI already presents the information of the notification. For example, in a mail application, you would not display a notification of new mails, if the user already has the inbox open and can select the new mails. Likewise, why display a notification if your user can already select a cell and open the view?

Notifications are meant to be set and forget.

**Comment by mohpor** [comment]
@LeoNatan, I remember when I was reviewing the library to what we can do to mitigate this problem and I came to the same conclusion. but:
1- We can provide this possibility for notifications other than alerts, because alerts shouldn't be dismissed without user's action IMHO,
2- I already prevent the app from displaying notifications, but there are cases where we would move to a view which makes the notification obsolete. In those cases, it would very much help the UX if we could dismiss the current notification as well!

**Comment by LeoNatan** [comment]
But even in Apple's case this is the case with their own implementation. If you receive a mail banner notification and while it is open, start the Mail app, the banner will also remain open until it closes.

I am not saying having this ability is not useful, just that it requires thinking.

**Comment by mohpor** [comment]
OK, point taken. Lets move on for now and see what we can do in the future. Thanks for your time and cheers as always.

**Comment by LeoNatan** [comment]
I will leave the the issue open. Perhaps in some time I will come back to it and think of something better. I am planning some major changes for this library eventually, and will look to incorporate this.

**Comment by mohpor** [comment]
Sounds great, good luck. Let me know if I could help.
