### ISSUE TITLE
Push to cocoapods

### ISSUE THREAD

**Issue by allaire** [LeoNatan/LNNotificationsUI#18]
Would be cool to push to cocoapods, currently pulling it directly from the github repo.

Thanks!

**Comment by LeoNatan** [comment]
I think accepted a PR with CocoaPods support? Since I am not familiar with CP, I would like to have some assistance.

**Comment by allaire** [comment]
See https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by cashmash** [comment]
yes would be cool :)

**Comment by FedeHenze** [comment]
Is it un cocoa pods?

**Comment by ryuheechul** [comment]
+1

**Comment by irosenb** [comment]
+1 :smile:

**Comment by ppaulojr** [comment]
:+1:  me too

**Comment by PankovSerge** [comment]
+1

**Comment by irosenb** [comment]
This library isn't technically on Cocoapods, but they do have a podspec. 

I just pointed at the git repo, and cocoapods successfully installed it. Like so: 
`pod 'LNNotificationsUI', :git => "https://github.com/LeoNatan/LNNotificationsUI.git"`

**Comment by PankovSerge** [comment]
@irosenb wow, i'll try it, thank 4 your solution

**Comment by LeoNatan** [comment]
Guys, as stated in my other project, I am not a fan of CocoaPods, and will not actively support it. I will however find the time to add Carthage support for a modern and better (in my view) management system.
