### ISSUE TITLE
Purpose of the drawer? Setting to disable it?

### ISSUE THREAD

**Issue by allaire** [LeoNatan/LNNotificationsUI#19]
In my head, the little drawer at the bottom is there to pull it down and reveal the full notification center on iOS. since this is not the case with this lib, I would like to hide it. Are you interested in a PR that adds a setting to disable it?

Thanks!

**Comment by LeoNatan** [comment]
I would actually prefer a PR with an implementation of the actual drawer purpose on iOS8 - present custom actions and text input. However I have not found the time to sit and do it.

**Comment by allaire** [comment]
A complete drawer would be cool, but much more time consuming to do. I plan to use LNNotificationsUI as my notification system when the user receives an notification when he's using the app, so hiding the drawer control is required in my case.

**Comment by LeoNatan** [comment]
Since the drawer is very easy to hide, let's keep it as is for now. I will find the time eventually to make the drawer. Perhaps iOS9 will inspire me.

**Comment by allaire** [comment]
@LeoNatan What do you mean by very easy to hide? I'm talking about https://github.com/LeoNatan/LNNotificationsUI/blob/master/LNNotificationsUI/LNNotificationsUI/LNNotificationBannerView.m#L211-L254

**Comment by LeoNatan** [comment]
Yes, and commenting these lines is very easy. :-)

**Comment by allaire** [comment]
@LeoNatan but since I'm using Cocoapods, each time I update, it will get overwritten, so it's not optimal :(

**Comment by LeoNatan** [comment]
My problem with such API is that I need to expose API which is not normally public API. None of the view hierarchy is exposed, nor are there any rendering settings available. So only place left is the notification itself, but that is not the correct place for this issue. Sorry

**Comment by allaire** [comment]
Hi Leo,

I think this will be inevitable at some point to expose an API to customize some elements of the UI like most librairies.

I'm open to discuss any API design with you so we can find a solution :)

Let me know, thanks!

**Comment by LeoNatan** [comment]
Well, the intent of this library is to give you as much of a native experience as possible. As long as iOS does not provide customization API, I am not sure I want to. 

Thanks

**Comment by allaire** [comment]
Heh that's your library, I think having a couple visual settings here and here is not a bad thing, but ultimately it's your call. Have a nice day!
