### ISSUE TITLE
LNNotificationAction in swift

### ISSUE THREAD

**Issue by ashutosh088** [LeoNatan/LNNotificationsUI#21]
Hi, I am new to iOS programming and using swift for my app.
I am using LNNotification for remote notification. My requirement is to navigate to a view controller when user tabs on a notification. Can you please some sample or example for this in swift ?

Thanks
Ash

**Comment by LeoNatan** [comment]
Hi Ash,

My implementation of actions is very similar to how `UIAlertController` handles actions. You should be able to learn from tutorials on that how to handle it with my framework.
What have you tried so far?

Leo
