### ISSUE TITLE
Memory Drainer

### ISSUE THREAD

**Issue by FISTUDIO-Dev** [LeoNatan/LNNotificationsUI#22]
The framework drains as much memory as over 50 MB!
Although not many leaks, it is still very shocking. 
![image](https://cloud.githubusercontent.com/assets/11804055/8764188/9b7cc15c-2e0a-11e5-86e6-53e01631c345.png)
![image](https://cloud.githubusercontent.com/assets/11804055/8764189/c69bf43e-2e0a-11e5-99e6-b31ef75be95e.png)

**Comment by LeoNatan** [comment]
Do you mean the demo app? It is not meant to be memory efficient but demonstrate the library. Feel free to submit pull requests with optimizations.
