### ISSUE TITLE
Add option for action buttons to show on banners

### ISSUE THREAD

**Issue by Rich2k** [LeoNatan/LNNotificationsUI#23]
In the same way you can pull down on system notifications to display action buttons, it would be great if we could do the same here, rather than only allowing action buttons in Alert style

**Comment by LeoNatan** [comment]
Agree with you that this is needed, and as with #14, I plan to do this at some point.

**Comment by LeoNatan** [comment]
Let's track this issue with the other one. I modified that title to indicate that both action buttons and input fields are needed.
