### ISSUE TITLE
Getting error in iOS9 dispatch_once

### ISSUE THREAD

**Issue by miscventura** [LeoNatan/LNNotificationsUI#24]
I'm getting an invoke_block error in iOS9 at the code below. Will this code be optimized for use in iOS9? Thanks.
LNNotificationAppSettings.h
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        LNNotificationAppSettings* __strong* rv = (LNNotificationAppSettings**)&LNNotificationDefaultAppSettings;
        *rv = [LNNotificationAppSettings new];
        (*rv).alertStyle = LNNotificationAlertStyleBanner;
        (*rv).soundEnabled = YES;
    });

**Comment by mehulparmar4ever** [comment]
did any1 Find Solution for this issue  ????

**Comment by rogcui** [comment]
Drag the LNNotificationsUI.framework file into your own project. That framework file is all you need.

**Comment by miscventura** [comment]
Great! Thanks for the reply.
I got mine working by changing things around a bit.
Not having any issues anymore.

#import "LNNotificationAppSettings.h"
![screen shot 2015-09-30 at 4 48 34 am](https://cloud.githubusercontent.com/assets/758323/10188639/d243b58a-672e-11e5-882c-56c3fb6c1a30.png)
#import "LNNotificationAppSettings.m"
![screen shot 2015-09-30 at 4 49 57 am](https://cloud.githubusercontent.com/assets/758323/10188641/d95f1d50-672e-11e5-880c-71e17afa0d82.png)

**Comment by LeoNatan** [comment]
BTW, I am not seeing an error on iOS 9.
