### ISSUE TITLE
'/Users/**/Documents/**/Carthage/Build/iOS/LNNotificationsUI.framework/LNNotificationsUI' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64

### ISSUE THREAD

**Issue by CodeEagle** [LeoNatan/LNNotificationsUI#27]
'/Users/**/Documents/**/Carthage/Build/iOS/LNNotificationsUI.framework/LNNotificationsUI' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64

**Comment by LeoNatan** [comment]
It means your project was compiled with BitCode, but LNNotificationsUI currently does not have it enabled. Enable BitCode and recompile.
