### ISSUE TITLE
Swipe the notification to ignore always acts like tapping. 

### ISSUE THREAD

**Issue by vickyrappier** [LeoNatan/LNNotificationsUI#29]
Swipe the notification to ignore always acts like tapping. 

I want to make the ship gesture very smooth so if user intends to ignore the message its not forcing him to enter.

Its erratic many times that ship is not smooth and always gets tapped.

Can we have the fix for this please.

**Comment by LeoNatan** [comment]
Hi,

Thanks for reporting this issue. I do not have time to take a look at this. Feel free to play around with the gesture recognizers. If you find a solution, do not fear sending a pull request.

Thanks,
Leo

**Comment by vickyrappier** [comment]
Can you redirect me as to which class can I handle this exactly, may be a lead to this will help me to update the Component.

**Comment by LeoNatan** [comment]
Look for the swipe gesture recognized.

**Comment by vickyrappier** [comment]
I am mostly interested in Pangesture rather than Swipe , actually similar like the smoothness to achieve when we to pan gesture to dismiss iOS Push notification / Local notification bar.

**Comment by LeoNatan** [comment]
Pan gesture makes more sense when there are options when pulling (as with iOS 8 and above). But this is not supported currently. There is already an issue existing for such an enhancement (#14).

**Comment by vickyrappier** [comment]
Appreciate if you can do this , as its best component out of all i have experience and well coded. Hats of for your development and looking for this pending feature.

**Comment by LeoNatan** [comment]
I don't have a lot of free time these days, and this is a major undertaking. Pull requests are welcome! :wink:

**Comment by vickyrappier** [comment]
No worries dear as explain I will definitely try I am just new to this Cocoapods, forking and all, will do if i can manage that,
