### ISSUE TITLE
Crash in +[LNNotificationAppSettings load] when statically compiled.

### ISSUE THREAD

**Issue by valeriyvan** [LeoNatan/LNNotificationsUI#31]
If you compile project just adding all LNNotificationsUI *.h and *m files to the project, +[LNNotificationAppSettings load] crashes on line initialising LNNotificationDefaultAppSettings pointer with BAD ACCESS exception. It seems like compiler puts const LNNotificationDefaultAppSettings pointer to read only memory segment. Removing const in LNNotificationDefaultAppSettings fixes crash. Would you accept pull request with such fix?

**Comment by LeoNatan** [comment]
I'll take a look, thanks!
