### ISSUE TITLE
iOS7 Support

### ISSUE THREAD

**Issue by Igor-Palaguta** [LeoNatan/LNNotificationsUI#35]
It can be used in iOS7 with small fixes. Don't you have plan to support iOS7 too?

**Comment by LeoNatan** [comment]
Actually, iOS 7 is supported. Dynamic framework are not, but you can add all source files directly to your iOS 7 project and it should work. This used to be officially stated in the readme file, as well as there was a demo project. I no longer wish to officially support iOS 7.
