### ISSUE TITLE
background music is not resumed after notification is dismissed

### ISSUE THREAD

**Issue by raymondchau-sinodynamic** [LeoNatan/LNNotificationsUI#37]
After researches, seem the problem is due to a missing code after the AVPlayer is stopped.

Suggestion:
add
[[AVAudioSession sharedInstance] setActive:NO withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:nil];

in - (void)audioPlayerDidFinishPlaying:(AVAudioPlayer *)player successfully:(BOOL)flag
of LNNotificationCenter

**Comment by LeoNatan** [comment]
@raymondchau-sinodynamic Do you mind submitting a pull request so I can accept?

**Comment by raymondchau-sinodynamic** [comment]
Thanks @LeoNatan .
Your library is really nice. I love it so much.

**Comment by LeoNatan** [comment]
Thanks!
