### ISSUE TITLE
Making some properties public

### ISSUE THREAD

**Issue by jyounus** [LeoNatan/LNNotificationsUI#40]
Hey there,

How about making the following properties public so that they can be modified?

```
static const NSTimeInterval LNNotificationAnimationDuration = 0.5;
static const NSTimeInterval LNNotificationFullDuration = 5.0;
static const NSTimeInterval LNNotificationCutOffDuration = 2.5;
```

I'm creating a Chat application, something similar to WhatsApp. Having the default duration of 5.0 and a cut off time of 2.5 is too long for me, especially if the user sends let's say 10 one line messages at once. 

Also, is there a way to cancel notifications that haven't been shown yet? I don't want the notification to show if the user is in a specific section of my app. I want to cancel all the pending notifications in that case.

Thanks for making this open source btw!

**Comment by LeoNatan** [comment]
How does it differ currently with iOS banners? I think my measurements of 2.5/5.0 were accurate, at least at the time of development.

There is currently no API to cancel all pending notifications for an app. It shouldn't be difficult to implement, but I have very little free time right now for this library. If you wish to submit a pull request for this, I'd appreciate it.

**Comment by jyounus** [comment]
I'm pretty sure it's exactly the same as iOS right now. However the Messages.app by Apple doesn't show any custom alerts while the app is open, if I'm not mistaken.

However WhatsApp uses a custom implementation and that feels like that the cut off time is around 1.5 rather than 2.5. I'm pretty sure they also debounce some in-app notifications, but I can handle that manually, outside of this lib.

Either way, it doesn't matter. I think some extra flexibility would be nice to allow devs to tweak the duration values. :)


Cool, if I do get a chance to implement this myself, I will definitely submit a PR.

**Comment by LeoNatan** [comment]
BTW, I see there already exists API for dismissing notifications.

```objectivec
- (void)clearPendingNotificationForApplictionIdentifier:(NSString*)appIdentifier;
- (void)clearAllPendingNotifications;
```

Do these methods not implement what you need? When entering the portions of UI where notifications are not needed, clear them.

**Comment by jyounus** [comment]
Oh wow, I totally didn't realise they existed, they should do exactly what I need!
Awesome! :D


Now I just need those constants changed so that I can actually modify their values. :)

**Comment by LeoNatan** [comment]
Exposing the *constants* as modifiable just doesn't sound right. 😉

Seriously though, the point of this library is to be as close to Apple's look and feel. This includes animation timing and duration. I would like to keep this rule here. WhatsApp's implementation, for example, feels foreign, and somewhat falls in the uncanny valley due to the liberties they have taken with presentation and drawing of their banners. Feel free to fork the lib and modify the values to your heart's content.

**Comment by jyounus** [comment]
Fair enough, if you want to strictly keep this lib as close to Apple's look and feel and not allow any modifications, then that's understandable. 

Thanks for your help anyway!
