### ISSUE TITLE
Pods not installing this library

### ISSUE THREAD

**Issue by vickyrappier** [LeoNatan/LNNotificationsUI#41]
Hi I am getting this error while installing through pods, this suddenly stopped. Can you please help as this app is in Appstore now and have to release the update.

[!] /usr/bin/git clone https://github.com/CodeEagle/LNNotificationsUI.git /var/folders/hv/xz_d5sf534s2t3c_xb2fx_4h0000gn/T/d20160316-6150-1kzwn8e --single-branch --depth 1 --branch 0.0.1

Cloning into '/var/folders/hv/xz_d5sf534s2t3c_xb2fx_4h0000gn/T/d20160316-6150-1kzwn8e'...
remote: Repository not found.
fatal: repository 'https://github.com/CodeEagle/LNNotificationsUI.git/' not found

**Comment by vickyrappier** [comment]
Ok i installed it using this reference link 'https://github.com/LeoNatan/LNNotificationsUI/issues/18'

By solution given by ironseb 

pod 'LNNotificationsUI', :git => "https://github.com/LeoNatan/LNNotificationsUI.git"


Can you confirm if this is okay :)

**Comment by LeoNatan** [comment]
Hi,

CocoaPods is not supported. So I cannot comment if correct because I am not familiar with CocoaPods. 

Consider using Carthage.
