### ISSUE TITLE
CocoaPods install: Git source not founded  

### ISSUE THREAD

**Issue by nigarcia88** [LeoNatan/LNNotificationsUI#42]
In the LNNotificationsUI.podspec.json file, can you fix the source-> git url ?

"https://github.com/CodeEagle/LNNotificationsUI.git" is shown like a not founded url.

Thanks!

**Comment by LeoNatan** [comment]
Hi,

I'll be removing support for CocoaPods soon. It will only support Carthage.

Will close this issue for now.
