### ISSUE TITLE
Module LNNotificationUI not found error. 

### ISSUE THREAD

**Issue by vickydhas** [LeoNatan/LNNotificationsUI#53]
Hello Leo,

I understand that you have stopped support for adding feature as IOS 10 already is coming with thsi implementation.

I have followed your instructions to add this library as I need this for my app which support 8.0 OS also so cannot use apples UsernotificationCenter component which is IOS 10.0 and above.

I am facing the module not found even if adding the library as project 
1) drag and drop to the main project
2) Adding in embedded binaries.
3) @import LNNotificationUI; 

I get the Module not found error still. Can help on this please.
<img width="788" alt="screen shot 2017-03-13 at 12 39 00 pm" src="https://cloud.githubusercontent.com/assets/834663/23841741/6ab9a48e-07ea-11e7-8b85-8a5b97dc0994.png">

**Comment by LeoNatan** [comment]
Have you added the framework as a dependency of you main project in build phases?

**Comment by vickydhas** [comment]
Yes please. Never mind I fixed it by manually taking the source files
rather drag and drop of project.

As I mentioned I want iOS 8,9 support so have to use this can't go with
apples thing as it's iOS 10 and above only.


-- 
Sent from my iPhone6+

**Comment by LeoNatan** [comment]
Adding source files is problematic because the framework has assets, and I'm not sure how I handle them in code. It should just work the way you did it.

**Comment by LeoNatan** [comment]
Ah I found the issue. 
It should be `@import LNNotificationsUI;`

**Comment by vickydhas** [comment]
Where to import , if you have managed to fixe in your code can you please let me know. so we use the default practise of importing project as Drag and drop.

**Comment by LeoNatan** [comment]
It was a spelling mistake on your part. Take a look at your screenshot, it is written incorrectly.

**Comment by vickydhas** [comment]
Okay I tried again by pasting from the Demo app that you have given but
still same issue.
-- 
Sent from my iPhone6+

**Comment by LeoNatan** [comment]
Does the demo app compile for you?

**Comment by vickydhas** [comment]
Yes please , thats strange and i know i am missing very basic thingy.

**Comment by vickydhas** [comment]
Only difference is mine is workspace based project and you have a project.
-- 
Sent from my iPhone6+
