### ISSUE TITLE
have a doubt in LNNotificationbannerwindow

### ISSUE THREAD

**Issue by solarisis** [LeoNatan/LNNotificationsUI#55]
you have a user tapped function which can be used to stop sound etc.. I am wondering if I can instantiate a view controller from this function... as in when I click the notification I should be able to navigate to another window .. how to achieve this?

**Comment by LeoNatan** [comment]
I am sorry, I don’t understand the problem or the title.

**Comment by solarisis** [comment]
u have a function called 
- (void)_userTappedNotification
{
    [[LNNotificationCenter defaultCenter] clearSound];
    
	[self _dismissNotificationViewWithCompletionBlock:_pendingCompletionHandler force:YES];
	
	if(_notificationView.currentNotification != nil && _notificationView.currentNotification.defaultAction.handler != nil)
	{
		_notificationView.currentNotification.defaultAction.handler(_notificationView.currentNotification.defaultAction);
	}
    
   
    
//    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
//    UIViewController *viewController;
//    viewController = [storyboard instantiateViewControllerWithIdentifier:@"PushVC"];
//    self.window.rootViewController = viewController;
//    [self.window makeKeyAndVisible];

    
}

how do I push a view controller when I click on this notification..

**Comment by LeoNatan** [comment]
This is internal framework API. You should be providing an action.

See:
https://github.com/LeoNatan/LNNotificationsUI/blob/master/LNNotificationsUI/LNNotificationsUI/LNNotification.h

Also, take a look at the example project.
