### ISSUE TITLE
Library not loaded, Reason: image not found

### ISSUE THREAD

**Issue by Kjuly** [LeoNatan/LNNotificationsUI#7]
Hi @LeoNatan , i've got an error:

> dyld: Library not loaded: @rpath/LNNotificationsUI.framework/LNNotificationsUI
  Referenced from: /private/var/mobile/Containers/Bundle/Application/8D250AEC-6661-423F-8391-CA4719E9F3D8/xxxxx.app/xxxxx
  Reason: image not found

I've followed ur steps to add `LNNotificationsUI.xcodeproj` to my project, and added `LNNotificationsUI.framework ` & `LNNotificationsUIAssets.xcassets` to the right place as below:

![screen shot 2014-11-19 at 11 14 39](https://cloud.githubusercontent.com/assets/867323/5100157/57f28c28-6fdd-11e4-9e70-768487229d3b.png)

And idea about this?

---
My envir is Xcode 6.0.1 (6A317) / Xcode 6.1 (6A1046a) with iOS 8 SDK. Target device is iPad 3 (simulator works).

**Comment by LeoNatan** [comment]
Guys, please see http://stackoverflow.com/questions/24002836/dyld-library-not-loaded-rpath-libswift-stdlib-core-dylib

This appears to happen to many people, even with Apple's own Swift dynamic libraries. Make sure to update your certificates at the Apple developer portal, and also make sure to set the signing identity of the library.

**Comment by kittany13** [comment]
hello there ... i have found some sort of solution for this problem :
i opend the .xcodeproj file , copied the project files, all the 15 file + the LNNotificationsUI.h.
changed the the LNNotificationsUI.h to:
#import "LNNotification.h"
#import "LNNotificationCenter.h"
#import "LNNotificationAppSettings.h"
#import "LNNotificationSettingsController.h"

that's all enjoy ... :)

**Comment by LeoNatan** [comment]
That's not a solution, that's cheating. :) You are statically linking the library now. That's not what is meant here. In your solution, remember to also take the asset files, or else images will not appear.

**Comment by kittany13** [comment]
first of all thanks for the great library of yours .....
i have tried 4 day long to solve the issue because i wanted this library so bad ... 
whene you solve this issue i'll gladly reuse it 👍

**Comment by LeoNatan** [comment]
This is an old issue, no longer reproducing. See main readme how to integrate in Xcode 7.
